#!/bin/bash

pacman_options="--needed --noconfirm"
packages_url=http://ahdiaz.euler.es/arch/installer
packages_install=$packages_url/packages.install
packages_uninstall=$packages_url/packages.uninstall
yaourt_url=https://aur.archlinux.org/packages/ya/yaourt/PKGBUILD
package_query_url=https://aur.archlinux.org/packages/pa/package-query/PKGBUILD

aur_install ()
{
    sudo pacman -S $pacman_options base-devel
    package_name=$1
    package_url=$2
    installed=`pacman -Qs $package_name`
    if [ -z "$installed" ]; then
        mkdir -p abs/$package_name
        curl $package_url -o abs/$package_name/PKGBUILD
        cd abs/$package_name
        makepkg -csi --noconfirm
        cd -
    fi
}

#sudo pacman-key --init
#sudo pacman-key --populate archlinux

sudo pacman -Syy
sudo pacman -S $pacman_options pacman
sudo pacman -Rs --noconfirm $(curl $packages_uninstall | grep -v "^#")

#aur_install "package-query" $package_query_url
#aur_install "yaourt" $yaourt_url
#sudo pacman -S $pacman_options yaourt

#yaourt -Sy
yaourt -Sua $pacman_options $(curl $packages_install | grep -v "^#")
